services:
  - type: web
    name: City-Wide-DarkStore-Network
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:5500 app:app
    envVars:
      - key: PORT
        value: 5500
    autoDeploy: true
    region: oregon
